<h1>Отзывы</h1>
<table class="table">
    <thead>
    <tr>
        <th>Ник</th>
        <th>Отзыв</th>
        <th>Опубликованно</th>
        <th>Удалить</th>
    </tr>
    </thead>
    <tbody>

    <?php foreach($reviews as $v):?>
        <tr>
            <td><?= $v->nickname?></td>
            <td><?= $v->reviews ?></td>
            <td><a href="<?=  $this->url('success', ['controller_name'=>'reviews','action_name'=>'switch','id'=>$v->id])?>"><?= $v->publish ? 'Видно': 'Не видно' ?></a></td>
            <td><a href="<?=  $this->url('success', ['controller_name'=>'reviews','action_name'=>'delete','id'=>$v->id])?>">Удалить</a></td>
        </tr>
    <?php endforeach;?>

    </tbody>


</table>