


   <div id="wrapper">
      <div id="content">
         <div class="main-page-title">
            <h1>Добро пожаловать в My shop</h1>
            <p>Самые низкие цены, самая быстрая доставка,</br>скидки постоянным клиентам</p>

            <div class="slider">
               <div class="bxslider">
                  <a href="#">
                     <div class="slider-img col-md-12">
                        <img src="../images/sl1.jpg" alt=""/>
                        <div class="slider-text col-md-5">
                           <h3>Nike Airmax 95 Green</h3>
                           <label>Имеют двойную подошву: в каждом из слоев воздух сжимается под разным давлением, что
                              снимает с ног нагрузку от столкновения с асфальтом, обеспечивает идеальное положение стопы
                              во время ходьбы и отличную амортизацию. </label>
                        </div>
                     </div>
                  </a>
                  <a href="#">
                     <div class="slider-img col-md-12">
                        <img src="../images/sl2.jpg" alt=""/>
                        <div class="slider-text col-md-5">
                           <h3>Nike Airmax 97 Grey</h3>
                           <label>Использовалась система видимого воздуха по всей стопе без ограничений и в которой она
                              стала обозримой со всех сторон. Air Max 97 также известны упрочненной конструкцией
                              тканевого верха, а три динамичные линии в виде светоотражающих полосок.</label>
                        </div>
                     </div>
                  </a>
                  <a href="#">
                     <div class="slider-img col-md-12">
                        <img src="../images/sl3.jpg" alt=""/>
                        <div class="slider-text col-md-5">
                           <h3>Nike Airmax 97 Grey</h3>
                           <label>Использовалась система видимого воздуха по всей стопе без ограничений и в которой она
                              стала обозримой со всех сторон. Air Max 97 также известны упрочненной конструкцией
                              тканевого верха, а три динамичные линии в виде светоотражающих полосок.</label>
                        </div>
                     </div>
                  </a>
                  <a href="#">
                     <div class="slider-img col-md-12">
                        <img src="../images/sl4.jpg" alt=""/>
                        <div class="slider-text col-md-5">
                           <h3>Nike Airmax 97 Grey</h3>
                           <label>Использовалась система видимого воздуха по всей стопе без ограничений и в которой она
                              стала обозримой со всех сторон. Air Max 97 также известны упрочненной конструкцией
                              тканевого верха, а три динамичные линии в виде светоотражающих полосок.</label>
                        </div>
                     </div>
                  </a>
                  <a href="#">
                     <div class="slider-img col-md-12">
                        <img src="../images/sl5.jpg" alt=""/>
                        <div class="slider-text col-md-5">
                           <h3>Nike Airmax 97 Grey</h3>
                           <label>Использовалась система видимого воздуха по всей стопе без ограничений и в которой она
                              стала обозримой со всех сторон. Air Max 97 также известны упрочненной конструкцией
                              тканевого верха, а три динамичные линии в виде светоотражающих полосок.</label>
                        </div>
                     </div>
                  </a>
               </div>
            </div>

            <!--         <div class="post-slider">-->
            <!--         <h2>Акционные товары</h2>-->
            <!--            </div>-->
         </div>
      </div>

