<h1>Тут добавляем</h1>
<form method="post"  enctype="multipart/form-data" >
    <input type="text" name="title" placeholder="Название">
    <input type="text" name="costoff" placeholder="Цена за ед.">
    <input type="file" name="path" >

    <label>Описание</label>
    <textarea name="description" id="" cols="30" rows="10"></textarea>
    <input type="hidden" name="category_id" value="<?= $this->category_id?>">






    <label><?= $this->error ?></label>
    <input type="submit" value="Отправить">
</form>
