<h1>Список товаров</h1>
<a href="<?= $this->url('success', ['controller_name'=>'products','action_name'=>'add','id'=>$this->category_id])?> " >
    <button class="btn-default">Добавить товар</button></a>


<table class="table">
    <thead>
    <tr>
        <th>Название</th>
        <th>Удалить</th>
        <th>Изменить</th>
    </tr>
    </thead>
    <tbody>

    <?php foreach($list as $v):?>
        <tr>
            <td><?= $v->title?></td>
            <td><a href="<?=  $this->url('success', ['controller_name'=>'products','action_name'=>'delete','id'=>$v->id])?>">Удалить</a></td>
            <td><a href="<?=  $this->url('success', ['controller_name'=>'products','action_name'=>'edit','id'=>$v->id])?>">Редактировать</a></td>
        </tr>
    <?php endforeach;?>

    </tbody>


</table>